//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET55.PetBlog.Server.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetBlogEntities4 : DbContext
    {
        public PetBlogEntities4()
            : base("name=PetBlogEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Articl_Words> Articl_Words { get; set; }
        public DbSet<ImgList> ImgList { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<PetComment> PetComment { get; set; }
        public DbSet<PetInfo> PetInfo { get; set; }
        public DbSet<PetServer> PetServer { get; set; }
        public DbSet<PetType> PetType { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
