//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET55.PetBlog.Server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetComment
    {
        public int ID { get; set; }
        public string Det { get; set; }
        public System.DateTime CommentTime { get; set; }
        public int UsersID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
