//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET55.PetBlog.Server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetInfo
    {
        public int ID { get; set; }
        public string ImgUrl { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Det { get; set; }
        public int Count { get; set; }
        public int PetTypeID { get; set; }
        public int UserInfoID { get; set; }
        public string Address { get; set; }
    
        public virtual PetType PetType { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
