//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET55.PetBlog.Server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.PetComment = new HashSet<PetComment>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
        public string Pwd { get; set; }
        public int Age { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public string HeadImg { get; set; }
        public string Eamil { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual ICollection<PetComment> PetComment { get; set; }
    }
}
