//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET55.PetBlog.Server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.News = new HashSet<News>();
            this.PetInfo = new HashSet<PetInfo>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public System.DateTime RegTime { get; set; }
        public string Eamil { get; set; }
        public string HeadUrl { get; set; }
    
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<PetInfo> PetInfo { get; set; }
    }
}
